server:
  port: 8081
  #servlet:
    #context-path: /springboot

#禁用thymeleaf模板引擎的缓存
spring:
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    druid:
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test-jdbc?useUnicode=true&characterEncoding=utf-8
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000





## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.asiainfo.springboot.model  # 注意：对应实体类的路径

asiainfo:
  hello:
    prefix: 您好
    suffix: 旅途快乐

